#ifndef MENU_HPP
#define MENU_HPP

#include "code_correction.hpp"
#include "matrix_operations.hpp"

#define CLEAR_SCREEN "\033[2J\033[1;1H"

/**
 * @file menu.hpp
 * @brief Header file for CLI-related functions.
 */

/**
 * @brief Clears the terminal screen.
 */
void clear_terminal();

/**
 * @brief Prints all code words generated by the provided generator matrix.
 *
 * This function prints all code words generated by the specified generator
 * matrix.
 *
 * @param gen The generator matrix.
 * @param n   The length of the codeword.
 * @param k   The dimension of the code.
 */
void printCodeWords(std::deque<std::deque<int>> gen, int n, int k);

/**
 * @brief Prints a polynomial representation.
 *
 * This function prints a polynomial representation of a binary sequence.
 *
 * @param poly The binary sequence to represent as a polynomial.
 */
void printPoly(std::deque<int> poly);

/**
 * @brief Prints plain text with code properties.
 *
 * This function prints plain text with code properties such as length,
 * dimension, and generator polynomial.
 *
 * @param n    The length of the codeword.
 * @param k    The dimension of the code.
 * @param poly The generator polynomial represented as a binary sequence.
 */
void printPlainText(int n, int k, std::deque<int> poly);

/**
 * @brief Gets new code parameters from the user.
 *
 * This function prompts the user to input new code parameters, including
 * length, dimension, and generator polynomial.
 *
 * @param n     The length of the codeword (updated).
 * @param k     The dimension of the code (updated).
 * @param value The new generator polynomial value (updated).
 */
void getNewPoly(int &n, int &k, int &value);

/**
 * @brief Initializes the main menu with default code parameters.
 *
 * This function initializes the main menu with default code parameters.
 *
 * @param n   The default length of the codeword.
 * @param k   The default dimension of the code.
 * @param gx  The default generator polynomial value.
 */
void initMenu(int n = 18, int k = 8, int gx = 1533);

/**
 * @brief Displays the option menu for CLI interaction.
 */
void optMenu();

/**
 * @brief Displays the main menu for CLI interaction.
 */
void menu();

#endif // MENU_HPP